[build]
  publish = ""

[[plugins]]
  package = "@netlify/plugin-image-optim"

  [plugins.inputs]
    # 图片优化配置
    quality = 80
    webp = true
    avif = true
    # 包含的图片路径
    include = ["static/img/*"]
    # 排除的图片路径
    exclude = []

[[plugins]]
  package = "@netlify/plugin-audio-optim"

  [plugins.inputs]
    # 音频优化配置
    bitrate = 128
    # 包含的音频路径
    include = ["static/source/*.mp3"]
    # 排除的音频路径
    exclude = []